LINUXINCLUDE += -I$(SAFELINUX_MODULES_ROOT)/include

ifeq (y,$(native_build))
KBUILD_EXTRA_SYMBOLS +=$(HDR_INSTAL_PATH)/../lib/security-modules-symbol/Module.symvers
endif

obj-m += apps_pinctrl.o
apps_pinctrl-objs := drivers/apps_pinctrl.o

obj-m += scm_user_intf.o
ifneq ($(KERNELRELEASE), "5.14.0")
ccflags-y += -I$(KERNEL_SRC)/drivers/firmware
endif
scm_user_intf-objs := drivers/scm_user_intf.o

obj-m += qcom_dload_mode.o
qcom_dload_mode-objs := drivers/qcom_dload_mode.o

obj-m += iommu_iova_map.o
iommu_iova_map-objs := drivers/iommu_iova_map.o

obj-m += vfio_iommu_qcom.o
vfio_iommu_qcom-objs := drivers/vfio_iommu_qcom.o

obj-m += kiumd.o
ifneq ($(KERNELRELEASE), "5.14.0")
ccflags-y += -I$(KERNEL_SRC)/drivers/iommu/arm
endif
kiumd-objs := drivers/kiumd.o

obj-m += qcom_uscmi.o
qcom_uscmi-objs := drivers/qcom_uscmi.o

obj-m += kryo_arm64_edac.o
kryo_arm64_edac-objs := drivers/kryo_arm64_edac.o

obj-m += kiumd_kgsl.o
kiumd_kgsl-objs := drivers/kiumd_kgsl.o

obj-m += profiler.o
profiler-objs := drivers/profiler.o

obj-m += qcom_ethqos_filter.o
qcom_ethqos_filter-objs := drivers/qcom_ethqos_filter.o

ifndef CONFIG_QCOM_DMABUF_HEAPS
obj-m			+= qcom_dma_heaps.o
qcom_dma_heaps-objs	:= drivers/qcom_dma_heap.o drivers/qcom_dt_parser.o drivers/qcom_sg_ops.o
qcom_dma_heaps-objs	+= drivers/qcom_carveout_heap.o
qcom_dma_heaps-objs	+= drivers/qcom_cma_heap.o
endif

obj-m += mhi_ep_net.o
mhi_ep_net-objs := drivers/mhi_ep_net.o
