SAFELINUX_CFG_MODULES_ROOT :=$(M)

############ UAPI ############
UAPI_DIR :=     uapi/misc
UAPI_INC :=	-I$(SAFELINUX_CFG_MODULES_ROOT)/include/$(UAPI_DIR)

############ COMMON ############
COMMON_DIR :=	include
COMMON_INC :=	-I$(SAFELINUX_CFG_MODULES_ROOT)/$(COMMON_DIR)

LINUX_INC +=	-Iinclude/linux

INCS +=		$(COMMON_INC) \
		$(UAPI_INC)

EXTRA_CFLAGS += $(INCS)

obj-m += drivers/apps_pinctrl.o
obj-m += drivers/iommu_iova_map.o
obj-m += drivers/scm_user_intf.o
obj-m += drivers/vfio_iommu_qcom.o
obj-m += drivers/kiumd.o
obj-m += drivers/qcom_uscmi.o

